apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
  labels:
    {{ include "ks.labels" $ | nindent 4 }}
type: Opaque
data: 
    mysql-root-password: {{ .Values.mysql.mysql_root_password | b64enc | quote }}