apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.appKubernetesIoService }}
  labels: {{ include "ks.labels" $ | nindent 4 }}
    app.kubernetes.io/service: {{ .Values.mysql.appKubernetesIoService }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  selector:
    {{- include "ks.selectorLabels" (merge (dict "service" .Values.mysql.appKubernetesIoService) $) | nindent 4 }}
